/**
 * @file Generates pools.md file for OpenClaw heartbeat consumption
 *
 * Creates a markdown file with top pools sorted by Bestly score and APR.
 * OpenClaw fetches this via HTTP during its heartbeat, reads the markdown
 * naturally, and uses it to inform LP management decisions.
 *
 * Output: /public/openclaw/pools.md
 *
 * Why markdown instead of JSON?
 * - LLMs read markdown naturally without parsing
 * - Can include contextual notes the agent reasons about
 * - Easier to maintain and debug
 */

import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';

interface PoolData {
  poolPair: string;
  protocolName: string;
  combinedAPR: number;
  tvl: number;
  volume24h: number | null;
  normalizedBestlyReturn: number | null;
  supplyUrl: string;
  poolAddress?: string;
}

/**
 * Format USD values for display
 */
function formatUSD(n: number | null): string {
  if (n === null || n === undefined || isNaN(n)) return '—';
  if (n >= 1_000_000_000) return `$${(n / 1_000_000_000).toFixed(2)}B`;
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
  if (n >= 1) return `$${n.toFixed(0)}`;
  return `$${n.toFixed(2)}`;
}

/**
 * Format percentage values
 */
function formatPct(n: number | null): string {
  if (n === null || n === undefined || isNaN(n)) return '—';
  return `${n >= 0 ? '+' : ''}${n.toFixed(2)}%`;
}

/**
 * Generate the markdown content for pools
 */
export function generatePoolsMarkdown(pools: PoolData[]): string {
  // Filter and sort by Bestly score (descending)
  const byBestly = [...pools]
    .filter(p => p.normalizedBestlyReturn != null && !isNaN(p.normalizedBestlyReturn))
    .sort((a, b) => (b.normalizedBestlyReturn ?? 0) - (a.normalizedBestlyReturn ?? 0))
    .slice(0, 10);

  // Sort by APR (descending)
  const byAPR = [...pools]
    .filter(p => p.combinedAPR > 0)
    .sort((a, b) => b.combinedAPR - a.combinedAPR)
    .slice(0, 10);

  // Sort by TVL (descending) - safest pools
  const byTVL = [...pools]
    .filter(p => p.tvl > 0)
    .sort((a, b) => b.tvl - a.tvl)
    .slice(0, 10);

  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 16);

  return `# 🦞 Monadly Top Pools

**Last Updated:** ${timestamp} UTC
**Data Source:** [monadly.xyz](https://monadly.xyz)

---

## Top 10 by Bestly Score (7-Day Real Return)

Bestly Score measures **net return after accounting for impermanent loss** in concentrated liquidity.
A positive Bestly means LPs actually made money; negative means IL ate the rewards.

| Rank | Pool | DEX | Bestly 7D | APR | TVL | Deposit Link |
|------|------|-----|-----------|-----|-----|--------------|
${byBestly.map((p, i) => `| ${i + 1} | ${p.poolPair} | ${p.protocolName} | **${formatPct(p.normalizedBestlyReturn)}** | ${p.combinedAPR.toFixed(0)}% | ${formatUSD(p.tvl)} | [Deposit](${p.supplyUrl}) |`).join('\n')}

---

## Top 10 by APR (Highest Yield)

⚠️ **Warning:** High APR doesn't guarantee profit! Check the Bestly score above to see if LPs are actually making money.

| Rank | Pool | DEX | APR | Bestly 7D | TVL |
|------|------|-----|-----|-----------|-----|
${byAPR.map((p, i) => `| ${i + 1} | ${p.poolPair} | ${p.protocolName} | **${p.combinedAPR.toFixed(0)}%** | ${formatPct(p.normalizedBestlyReturn)} | ${formatUSD(p.tvl)} |`).join('\n')}

---

## Top 10 by TVL (Most Liquid / Safest)

Higher TVL generally means lower slippage and more mature pools.

| Rank | Pool | DEX | TVL | APR | Bestly 7D |
|------|------|-----|-----|-----|-----------|
${byTVL.map((p, i) => `| ${i + 1} | ${p.poolPair} | ${p.protocolName} | **${formatUSD(p.tvl)}** | ${p.combinedAPR.toFixed(0)}% | ${formatPct(p.normalizedBestlyReturn)} |`).join('\n')}

---

## Notes for AI Agents

### Reading This Data
- **Bestly > 0%** = LPs made money after IL. The pool is healthy.
- **Bestly < 0%** = IL exceeded rewards. LPs lost money despite high APR.
- **High APR + Negative Bestly** = Dangerous! The yield looks attractive but LPs are losing.
- **Stable pairs** (USDC/USDT, etc.) have minimal IL risk but lower returns.

### Suggested Actions
1. **For new positions:** Prefer pools with positive Bestly AND high TVL
2. **For existing positions:** If your pool's Bestly turned negative, consider exiting
3. **For yield hunting:** Sort by APR but filter for Bestly > 0
4. **For safety:** Sort by TVL, these pools have proven liquidity

### Data Freshness
- This file updates every 10 minutes
- Real-time data available at [monadly.xyz](https://monadly.xyz)
- For historical trends, check the sparkline charts on the dashboard

---

*Generated by Monadly for OpenClaw integration*
`;
}

/**
 * Write pools.md to the public directory
 */
export async function writePoolsMd(pools: PoolData[], basePath: string = process.cwd()): Promise<void> {
  const outputDir = join(basePath, 'public', 'openclaw');
  const outputPath = join(outputDir, 'pools.md');

  // Ensure directory exists
  await mkdir(outputDir, { recursive: true });

  // Generate and write the markdown
  const markdown = generatePoolsMarkdown(pools);
  await writeFile(outputPath, markdown, 'utf-8');

  console.log(`[pools-md] Written ${outputPath} with ${pools.length} pools`);
}
